package com.liferay.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.services.model.Applicant;
import com.liferay.services.service.ApplicantLocalServiceUtil;

/**
 * The extended model base implementation for the Applicant service. Represents a row in the &quot;t_Applicant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplicantImpl}.
 * </p>
 *
 * @author Suresh Kumar
 * @see ApplicantImpl
 * @see com.liferay.services.model.Applicant
 * @generated
 */
public abstract class ApplicantBaseImpl extends ApplicantModelImpl
    implements Applicant {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a applicant model instance should use the {@link Applicant} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            ApplicantLocalServiceUtil.addApplicant(this);
        } else {
            ApplicantLocalServiceUtil.updateApplicant(this);
        }
    }
}
