package com.liferay.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Applicant service. Represents a row in the &quot;t_Applicant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.services.model.impl.ApplicantModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.services.model.impl.ApplicantImpl}.
 * </p>
 *
 * @author Suresh Kumar
 * @see Applicant
 * @see com.liferay.services.model.impl.ApplicantImpl
 * @see com.liferay.services.model.impl.ApplicantModelImpl
 * @generated
 */
public interface ApplicantModel extends BaseModel<Applicant> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a applicant model instance should use the {@link Applicant} interface instead.
     */

    /**
     * Returns the primary key of this applicant.
     *
     * @return the primary key of this applicant
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this applicant.
     *
     * @param primaryKey the primary key of this applicant
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the applicant ID of this applicant.
     *
     * @return the applicant ID of this applicant
     */
    public long getApplicantId();

    /**
     * Sets the applicant ID of this applicant.
     *
     * @param applicantId the applicant ID of this applicant
     */
    public void setApplicantId(long applicantId);

    /**
     * Returns the first name of this applicant.
     *
     * @return the first name of this applicant
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this applicant.
     *
     * @param firstName the first name of this applicant
     */
    public void setFirstName(String firstName);

    /**
     * Returns the middle name of this applicant.
     *
     * @return the middle name of this applicant
     */
    @AutoEscape
    public String getMiddleName();

    /**
     * Sets the middle name of this applicant.
     *
     * @param middleName the middle name of this applicant
     */
    public void setMiddleName(String middleName);

    /**
     * Returns the last name of this applicant.
     *
     * @return the last name of this applicant
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this applicant.
     *
     * @param lastName the last name of this applicant
     */
    public void setLastName(String lastName);

    /**
     * Returns the qualifications of this applicant.
     *
     * @return the qualifications of this applicant
     */
    @AutoEscape
    public String getQualifications();

    /**
     * Sets the qualifications of this applicant.
     *
     * @param qualifications the qualifications of this applicant
     */
    public void setQualifications(String qualifications);

    /**
     * Returns the address line1 of this applicant.
     *
     * @return the address line1 of this applicant
     */
    @AutoEscape
    public String getAddressLine1();

    /**
     * Sets the address line1 of this applicant.
     *
     * @param addressLine1 the address line1 of this applicant
     */
    public void setAddressLine1(String addressLine1);

    /**
     * Returns the address line2 of this applicant.
     *
     * @return the address line2 of this applicant
     */
    @AutoEscape
    public String getAddressLine2();

    /**
     * Sets the address line2 of this applicant.
     *
     * @param addressLine2 the address line2 of this applicant
     */
    public void setAddressLine2(String addressLine2);

    /**
     * Returns the city of this applicant.
     *
     * @return the city of this applicant
     */
    @AutoEscape
    public String getCity();

    /**
     * Sets the city of this applicant.
     *
     * @param city the city of this applicant
     */
    public void setCity(String city);

    /**
     * Returns the street of this applicant.
     *
     * @return the street of this applicant
     */
    @AutoEscape
    public String getStreet();

    /**
     * Sets the street of this applicant.
     *
     * @param street the street of this applicant
     */
    public void setStreet(String street);

    /**
     * Returns the post code of this applicant.
     *
     * @return the post code of this applicant
     */
    @AutoEscape
    public String getPostCode();

    /**
     * Sets the post code of this applicant.
     *
     * @param postCode the post code of this applicant
     */
    public void setPostCode(String postCode);

    /**
     * Returns the create date of this applicant.
     *
     * @return the create date of this applicant
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this applicant.
     *
     * @param createDate the create date of this applicant
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this applicant.
     *
     * @return the modified date of this applicant
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this applicant.
     *
     * @param modifiedDate the modified date of this applicant
     */
    public void setModifiedDate(Date modifiedDate);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Applicant applicant);

    public int hashCode();

    public CacheModel<Applicant> toCacheModel();

    public Applicant toEscapedModel();

    public String toString();

    public String toXmlString();
}
