package com.liferay.services.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.services.model.Applicant;
import com.liferay.services.service.ApplicantLocalService;
import com.liferay.services.service.ApplicantService;
import com.liferay.services.service.persistence.ApplicantPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the applicant local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.services.service.impl.ApplicantLocalServiceImpl}.
 * </p>
 *
 * @author Suresh Kumar
 * @see com.liferay.services.service.impl.ApplicantLocalServiceImpl
 * @see com.liferay.services.service.ApplicantLocalServiceUtil
 * @generated
 */
public abstract class ApplicantLocalServiceBaseImpl extends BaseLocalServiceImpl
    implements ApplicantLocalService, IdentifiableBean {
    @BeanReference(type = ApplicantLocalService.class)
    protected ApplicantLocalService applicantLocalService;
    @BeanReference(type = ApplicantService.class)
    protected ApplicantService applicantService;
    @BeanReference(type = ApplicantPersistence.class)
    protected ApplicantPersistence applicantPersistence;
    @BeanReference(type = CounterLocalService.class)
    protected CounterLocalService counterLocalService;
    @BeanReference(type = ResourceLocalService.class)
    protected ResourceLocalService resourceLocalService;
    @BeanReference(type = ResourceService.class)
    protected ResourceService resourceService;
    @BeanReference(type = ResourcePersistence.class)
    protected ResourcePersistence resourcePersistence;
    @BeanReference(type = UserLocalService.class)
    protected UserLocalService userLocalService;
    @BeanReference(type = UserService.class)
    protected UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ApplicantLocalServiceClpInvoker _clpInvoker = new ApplicantLocalServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.liferay.services.service.ApplicantLocalServiceUtil} to access the applicant local service.
     */

    /**
     * Adds the applicant to the database. Also notifies the appropriate model listeners.
     *
     * @param applicant the applicant
     * @return the applicant that was added
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public Applicant addApplicant(Applicant applicant)
        throws SystemException {
        applicant.setNew(true);

        return applicantPersistence.update(applicant, false);
    }

    /**
     * Creates a new applicant with the primary key. Does not add the applicant to the database.
     *
     * @param applicantId the primary key for the new applicant
     * @return the new applicant
     */
    public Applicant createApplicant(long applicantId) {
        return applicantPersistence.create(applicantId);
    }

    /**
     * Deletes the applicant with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param applicantId the primary key of the applicant
     * @return the applicant that was removed
     * @throws PortalException if a applicant with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    public Applicant deleteApplicant(long applicantId)
        throws PortalException, SystemException {
        return applicantPersistence.remove(applicantId);
    }

    /**
     * Deletes the applicant from the database. Also notifies the appropriate model listeners.
     *
     * @param applicant the applicant
     * @return the applicant that was removed
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    public Applicant deleteApplicant(Applicant applicant)
        throws SystemException {
        return applicantPersistence.remove(applicant);
    }

    public DynamicQuery dynamicQuery() {
        Class<?> clazz = getClass();

        return DynamicQueryFactoryUtil.forClass(Applicant.class,
            clazz.getClassLoader());
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return applicantPersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return applicantPersistence.findWithDynamicQuery(dynamicQuery, start,
            end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return applicantPersistence.findWithDynamicQuery(dynamicQuery, start,
            end, orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return applicantPersistence.countWithDynamicQuery(dynamicQuery);
    }

    public Applicant fetchApplicant(long applicantId) throws SystemException {
        return applicantPersistence.fetchByPrimaryKey(applicantId);
    }

    /**
     * Returns the applicant with the primary key.
     *
     * @param applicantId the primary key of the applicant
     * @return the applicant
     * @throws PortalException if a applicant with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    public Applicant getApplicant(long applicantId)
        throws PortalException, SystemException {
        return applicantPersistence.findByPrimaryKey(applicantId);
    }

    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return applicantPersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns a range of all the applicants.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
     * </p>
     *
     * @param start the lower bound of the range of applicants
     * @param end the upper bound of the range of applicants (not inclusive)
     * @return the range of applicants
     * @throws SystemException if a system exception occurred
     */
    public List<Applicant> getApplicants(int start, int end)
        throws SystemException {
        return applicantPersistence.findAll(start, end);
    }

    /**
     * Returns the number of applicants.
     *
     * @return the number of applicants
     * @throws SystemException if a system exception occurred
     */
    public int getApplicantsCount() throws SystemException {
        return applicantPersistence.countAll();
    }

    /**
     * Updates the applicant in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param applicant the applicant
     * @return the applicant that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public Applicant updateApplicant(Applicant applicant)
        throws SystemException {
        return updateApplicant(applicant, true);
    }

    /**
     * Updates the applicant in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param applicant the applicant
     * @param merge whether to merge the applicant with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
     * @return the applicant that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    public Applicant updateApplicant(Applicant applicant, boolean merge)
        throws SystemException {
        applicant.setNew(false);

        return applicantPersistence.update(applicant, merge);
    }

    /**
     * Returns the applicant local service.
     *
     * @return the applicant local service
     */
    public ApplicantLocalService getApplicantLocalService() {
        return applicantLocalService;
    }

    /**
     * Sets the applicant local service.
     *
     * @param applicantLocalService the applicant local service
     */
    public void setApplicantLocalService(
        ApplicantLocalService applicantLocalService) {
        this.applicantLocalService = applicantLocalService;
    }

    /**
     * Returns the applicant remote service.
     *
     * @return the applicant remote service
     */
    public ApplicantService getApplicantService() {
        return applicantService;
    }

    /**
     * Sets the applicant remote service.
     *
     * @param applicantService the applicant remote service
     */
    public void setApplicantService(ApplicantService applicantService) {
        this.applicantService = applicantService;
    }

    /**
     * Returns the applicant persistence.
     *
     * @return the applicant persistence
     */
    public ApplicantPersistence getApplicantPersistence() {
        return applicantPersistence;
    }

    /**
     * Sets the applicant persistence.
     *
     * @param applicantPersistence the applicant persistence
     */
    public void setApplicantPersistence(
        ApplicantPersistence applicantPersistence) {
        this.applicantPersistence = applicantPersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the resource remote service.
     *
     * @return the resource remote service
     */
    public ResourceService getResourceService() {
        return resourceService;
    }

    /**
     * Sets the resource remote service.
     *
     * @param resourceService the resource remote service
     */
    public void setResourceService(ResourceService resourceService) {
        this.resourceService = resourceService;
    }

    /**
     * Returns the resource persistence.
     *
     * @return the resource persistence
     */
    public ResourcePersistence getResourcePersistence() {
        return resourcePersistence;
    }

    /**
     * Sets the resource persistence.
     *
     * @param resourcePersistence the resource persistence
     */
    public void setResourcePersistence(ResourcePersistence resourcePersistence) {
        this.resourcePersistence = resourcePersistence;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        PersistedModelLocalServiceRegistryUtil.register("com.liferay.services.model.Applicant",
            applicantLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "com.liferay.services.model.Applicant");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
    }

    protected Class<?> getModelClass() {
        return Applicant.class;
    }

    protected String getModelClassName() {
        return Applicant.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = applicantPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
